website:
  image: php:5.6-apache
  volumes:
    - ./p5.js-website:/var/www/html/
    - ./p5.js:/var/p5.js
  ports:
    - "80:80"
p5:
  build: .
  working_dir: /var/p5.js
  command: /var/p5.js/p5-website-bridge/start.sh
  volumes:
    - ./p5.js:/var/p5.js/
    - ./p5.js-website:/var/www/html/
    - ./p5-website-bridge:/var/p5.js/p5-website-bridge/
