website:
  image: php:5.6-apache
  volumes:
    - ./p5.js-website:/var/www/html/:ro
    - ./p5.js:/var/p5.js:ro
    - ./php/etc:/usr/local/etc/php:ro
  ports:
    - "8000:80"
  environment:
    - PHP_P5_SITE_ROOT=/
p5:
  build: .
  working_dir: /var/p5.js
  entrypoint: node /var/p5.js/p5-website-bridge/entrypoint.js
  command: node /var/p5.js/p5-website-bridge/start.js
  volumes:
    - ./p5.js:/var/p5.js/
    - ./p5.js-website:/var/www/html/
    - ./p5-website-bridge:/var/p5.js/p5-website-bridge/
  environment:
    # Argh, bash doesn't export the UID environment variable, so the
    # user will have to manually export it.
    - HOST_UID
    # bash exports USER, so at least that part can be automated.
    - HOST_USER=$USER
